---
title: 'Probability: Homework 2'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{center}
\textbf{Nick Williams \\
ntw2117}
\end{center}

## Problem 1: 

(1) By definition, a probability mass function must satisify $\sum_{X \leq x} f(t) = 1$, if $x \in \{0, 1, 2, ...\}$ In addition, $k$ must be positive because $f(t) > 0$ for $f(t)$ to be a pmf. 

$$
\text{thus, } \sum_{i = 0}^{\infty} \frac{k}{2^x} = 1 
$$

By the common form of the geometric series: $a = \frac{k}{2^0}; r = \frac{1}{2}$

$$
\begin{aligned}
  1 &= \frac{a}{1 - r} \\
  1 &= \frac{k}{1 - 1/2} \\
  1 &= \frac{k}{1/2} \\
  k &= \frac{1}{2} \\
\end{aligned}
$$

(2) 

$$
f(x) = \frac{c}{x}
$$

If $f(x)$ is a pdf by definition, $\sum_X \leq x f(x) = 1$ and a common ratio should exist, if $c > 0$ then

$$
\begin{aligned}
  S_n &= \frac{c}{x_n} \\
  S_1 &= \frac{c}{1}, S_2 = \frac{c}{2}, S_3 = \frac{c}{3} 
\end{aligned}
$$

$$
\begin{aligned}
r_1 = S_2 / S_1 &= \frac{c}{2} \times \frac{1}{c} = \frac{1}{2} \\
r_2 = S_3 / S_2 &= \frac{c}{3} \times \frac{2}{c} = \frac{2}{3} \\
r_1 &\neq r_2
\end{aligned}
$$

There is no common ratio, $r$, the series therefore diverges and thus does not sum to 1 meaning $f(x) = \frac{c}{x}$ cannot be a probability density function. 

\newpage

## Problem 2: 

(1) For $f(t)$ to be a pdf, $\int_{-\infty}^{\infty}f(t)dt = 1$ and $f(t) > 0$, thus $c > 0$

$$
\begin{aligned}
  1 &= \int_{0}^{\infty}ce^{-2t}dt \\
    &= c \int_{0}^{\infty}e^{-2t}dt \\
    &= c \int_0^{\infty} e^u -\frac{1}{2}du \\
    &= c \int_0^{\infty} \frac{-e^u}{2}du \\
    &= \frac{-c}{2} \int_0^{\infty} e^udu \\
    &= \bigg[-\frac{1}{2}ce^{-2t}\bigg]_{0}^{\infty} \\
    &= \lim_{t \rightarrow \infty} \big(-\frac{1}{2}ce^{-2t}\big) - \big(-\frac{1}{2}c\big) \\
    &= 0 + \frac{1}{2}c \\
  c &= 2
\end{aligned}
$$

(2) The corresponding cdf of $f(x)$, $F(x)$ is the integral of $f(x)$, thus: 

$$
F(x) = P(X\leq x) =  -e^{-2t} \text{, where } 0 < t < \infty
$$ 

## Problem 3: 

If $f(t)$ and $g(t)$ are pdfs then: 

$$
\int_{-\infty}^{\infty} f(t)dt = 1 \text{ and } \int_{-\infty}^{\infty} g(t)dt = 1
$$

If $a \geq 0$ and $b \geq 0$ are constants satisfying $a + b = 1$ then, $a = 1 - b$. If $af(t) + bg(t)$ is a pdf then: 

$$
\begin{aligned}
   1 &= \int_{-\infty}^{\infty} a f(t) + \int_{-\infty}^{\infty} bg(t) \\
    &= a \int_{-\infty}^{\infty}f(t) + b \int_{-\infty}^{\infty} g(t) \\
    &= (1 - b) \int_{-\infty}^{\infty}f(t) + b \int_{-\infty}^{\infty} g(t) \\
    &= (1 - b)(1) + b(1) \\
    &= 1 - b + b \\
    &= 1
\end{aligned}
$$

## Problem 4: 

(1) For $F(t) = (1 - \frac{1}{1 + t}) \text{ } I\{t \geq0\}$ to be a cdf, it must satisfy:

  a. $\lim_{t\rightarrow \infty} F(t) = 1$ and $\lim_{t \rightarrow -\infty} F(t) = 0$:  
  
$$
\begin{aligned}
  1 &= \lim_{t \rightarrow \infty} (1 - \frac{1}{1 + t}) & 0 &= \lim_{t \rightarrow -\infty} (1 - \frac{1}{1 + t})I\{t \geq     0\} \\
  &= 1 - \lim_{t \rightarrow \infty} \frac{1}{1 + t}     &   &= 1 - \lim_{t \rightarrow 0} \frac{1}{1 + t} \\
  &= 1 - \lim_{t \rightarrow \infty} \frac{1}{1 + t}     &   &= 1 -\frac{1}{1 + 0} \\ 
  &= 1 + 0                                               &   &= 1 - 1 \\
  &= 1                                                   &   &= 0
\end{aligned}
$$
  
  b. $F(t)$ is a non-decreasing function i.e., for any $t_1 < t_2$, $F(t_1) \leq F(t_2)$:  
  
$$
\begin{aligned}
  F(t_2) - F(t_1) &\geq 0 \\
  \int_{-\infty}^{t_2} f(t_2)I\{t \geq 0\}dt - \int_{-\infty}^{t_1} f(t_1)I\{t \geq 0\}dt & \geq & f(t) = & \frac{d}{dt}F(t)     = \frac{1}{(1 + t)^2} \\
  \int_0^{t_2} f(t_2)dt - \int_0^{t_1} f(t_1)dt & \geq \\
  \int_0^{t_2} \frac{1}{(1 + t)^2}dt - \int_0^{t_1} \frac{1}{(1 + t)^2}dt & \geq \\
  \int_{t_1}^{t_2} \frac{1}{(1 + t)^2}dt &\geq \\
  (1 - \frac{1}{1 + t_2}) - (1 - \frac{1}{1 + t_1}) &\geq \\
  -\frac{1}{1 + t_2} + \frac{1}{1 + t_1} &\geq 0 \\
\end{aligned}
$$
  
  c. $F(t)$ is right continous, for any $t_0 \in (-\infty, \infty), \lim_{t \rightarrow +t_0} F(t) = F(t_0)$: 
  
$$
\begin{aligned}
  \lim_{t \rightarrow + t_0} \int_{-\infty}^t f(t)dt &= \int_{-\infty}^{t_0} f(t)dt \\
  \lim_{t \rightarrow + t_0} \int_{0}^t f(t)dt       &= \int_{0}^{t_0} f(t)dt \\
  \int_{0}^{t_0} f(t)dt                              &= \int_{0}^{t_0} f(t)dt \\
\end{aligned}
$$
  
(2) The pdf, $f(t)$, of $F(t)$ is the derivative of $F(t)$, $\frac{d}{dt}F(t)$: 

$$
\begin{aligned}
  f(t) &= \frac{d}{dt} F(t) \\
       &= \frac{d}{dt} (1 - \frac{1}{1 + t}) \\
       &= \frac{d}{dt}(1) - \frac{d}{dt} (1 + t)^{-1} \\
       &= -(-(1 + t)^{-2}) \\ 
       &= \frac{1}{(1 + t)^2}
\end{aligned}
$$

\newpage

## Problem 5:

(1)

$$
\begin{aligned}
  f(x) = P(X = x) = 
  \begin{cases}
    c(x + 1) &\text{ for } 0, 1, 2, 3, 4, 5 \\
           0 &\text{ otherwise}
  \end{cases}
\end{aligned}
$$

Because $f(x) > 0$ then $c > 0$. In addition, by the definition of a probability mass function: 

$$
\begin{aligned}
  1 &= \sum_x f(x) \\
    &= \sum_x c(x + 1) \\
    &= \sum_{x = 0}^5 = c(x + 1) \\
    &= c + 2c + 3c + 4c + 5c + 6c \\
    &= 21c \\
  c &= \frac{1}{21}
\end{aligned}
$$

(2)

$$
\begin{aligned}
  F(x) = P(X \leq x)= \sum_{X \leq x} \frac{x + 1}{21}
\end{aligned}
$$

(3)

$$
\begin{aligned}
  P(X > 2) = P(X \geq 3) &= 1 - P(X \leq 2) \\
                         &= 1 - \sum_{x = 0}^{2} \frac{x + 1}{21} \\
                         &= 1 - \frac{1}{21} + \frac{2}{21} + \frac{3}{21} \\
                         &= 0.7143
\end{aligned}
$$

\newpage

## Problem 6

(1) Because $f(x) \geq 0$, $c > 0$. In addition $\int_{-\infty}^{\infty} f(x)dx = 1$, thus

$$
\begin{aligned}
  1 &= \int_{-\infty}^{\infty} f(x)dx \\
    &= \int_{-\infty}^{\infty} c(1 + x)^{-5}I\{x \geq 0\} \\
    &= \int_0^{\infty} c(1 + x)^{-5} \\
    &= c \int_0^{\infty} (1 + x)^{-5} \\
    &= \bigg[c \times \frac{(1 + x)^{-4}}{-4} \bigg]_0^{\infty} \\
    &= \lim_{x \rightarrow \infty} \bigg( c \times \frac{1}{-4(1 + x)^{4}} \bigg) - \bigg(c \times \frac{1}{-4(1 + 0)^{4}}         \bigg) \\
    &= 0 + \frac{1}{4}c \\
  c &= 4
\end{aligned}
$$

(2) $F(x)$ is the integral of $f(x)$

$$
F(x) = P(X \leq x) = 4\bigg(\frac{1}{-4(1 + x)^4}\bigg) = -\frac{1}{(x + 1)^4}
$$

(3)

$$
\begin{aligned}
  P(0.4 < x < 0.45) & = \int_{\infty}^{0.45}f(x)dx - \int_{-\infty}^{0,40}f(x)dx \\
                    &= \int_{0.40}^{0.45} f(x)dx \\
                    &= \big[F(x)\big]_{0.4}^{0.45} \\
                    &= -\frac{1}{(0.45+1)^4} - \bigg(-\frac{1}{(0.4+1)^4}\bigg) \\
                    &= -0.2262 + 0.2603 \\
                    &= 0.0341
\end{aligned}
$$

The probability of a flaw occuring between 0.4 and 0.45 meters is 0.0341

\newpage

## Problem 7

If $g(x)$ is a pdf then it must satisfy: 

(1) $g(x) \geq 0$ for all $x \in (-\infty, \infty)$  

$$
g(x) = \frac{f(x)I\{x \geq x_0\}}{1 - F(x_0)}
$$  

If $f(x)$ and $F(x)$ are the pdf and cdf of random variable $X$ then $f(x)I\{x \geq x_0\} \geq 0$ and $1 >F(x_0) > 0$, then 

$$
g(x) \geq 0 \text{ for all } x
$$

(2) $\int_{-\infty}^{\infty} g(x)dx = 1$ where $x_0$ is fixed 

$$
\begin{aligned}
  1 &= \int_{-\infty}^{\infty} g(x)dx \\
    &= \int_{-\infty}^{\infty} \frac{f(x)I\{x \geq x_0\}}{1 - F(x_0)}dx \\
    &= \frac{1}{1 - F(x_0)} \int_{-\infty}^{\infty} f(x)I\{x \geq x_0 \}dx \\
    &= \frac{1}{1 - F(x_0)} \int_{x_0}^{\infty} f(x)dx \\
    &= \bigg[\frac{F(x)}{1 - F(x_0)} \bigg]_{x_0}^{\infty} \\
    &= \frac{1}{1 - 0} \\
    &= 1
\end{aligned}
$$

The cdf of $g(x)$ = $G(x)$ 

$$
\begin{aligned}
  G(x) &= \int_{-\infty}^{\infty} g(x)dx \\
       &= \frac{F(x)}{1 - F(x_0)}
\end{aligned}
$$






